In [1]:
import pyreadstat
import os
import pandas as pd

In [2]:
# Load RCT data file (preprocessed by Gemma Lewis)
dtafile = '../../data/trial_data/data_merged_clean_13.dta'
df, meta = pyreadstat.read_dta(dtafile)

In [3]:
# Whithdrawal
print(str((df['withdrew']==1).sum()) + ' patients chose to withdraw at some point during the study.')

124 patients chose to withdraw at some point during the study.

In [4]:
# Import healthcare data from patient questionnaire at 6-week and 12-week follow-up
folder_path = '../../data/trial_data/Healthcare data from patient questionnaire/'

# List all files in the folder
health_data_files = [f for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]
display(health_data_files)

# The patient questionnaire includes the following topics:
# Hospital care - PANDA_RUQ_HospitalStay, PANDA_RUQ_A&E, PANDA_RUQ_HospitalOutpatient
# Community-based NHS care - PANDA_RUQ_CommunityCare
# Home visit - PANDA_RUQ_HomeVisits

# We are interested in psychotherapy as an other interventions for treating depression
therapy_variables = ['counselling', 'f2fCBT', 'compCBT']

# Import data about therapy at 6-week and 12-week follow-up
list_df_therapy = []
merged_df_therapy = pd.DataFrame()
for i in ['2','3']:
    dtafile = folder_path +  'PANDA_RUQ_CommunityCare_FU' + i + '.dta'
    df_tmp, meta = pyreadstat.read_dta(dtafile)
    therapy_variables_in_df = ['identifier']
    for k in therapy_variables:
        therapy_variables_in_df = therapy_variables_in_df + [l for l in df_tmp if (k in l and 'location' not in l)]
    
    df_therapy = df_tmp[therapy_variables_in_df]
    list_df_therapy.append(df_therapy)
    
merged_df_therapy = pd.merge(list_df_therapy[0], list_df_therapy[1], on='identifier', how='outer')
merged_df_therapy['identifier_n'] = pd.to_numeric(merged_df_therapy['identifier'])

# Merge with other RCT data
merged_df = pd.merge(df, merged_df_therapy, on='identifier_n', how='outer')

['PANDA_RUQ_CommunityCare_FU3.dta',
 'PANDA_RUQ_CommunityCare_FU2.dta',
 'PANDA_RUQ_HospitalStay_FU2.dta',
 'PANDA_RUQ_HospitalStay_FU3.dta',
 'PANDA_RUQ_HomeVisits_FU3.dta',
 'PANDA_RUQ_HomeVisits_FU2.dta',
 'PANDA_RUQ_A&E_FU2.dta',
 'PANDA_RUQ_A&E_FU3.dta',
 'PANDA_RUQ_HospitalOutpatient_FU3.dta',
 'PANDA_RUQ_HospitalOutpatient_FU2.dta']

In [5]:
# A limited number of patients underwent psychotherapy during the study,
# hence we did not conduct subsample analyses. 
for i in ['6wks', '12wks']:
    merged_df['therapy' + i] = pd.to_numeric((merged_df[[l for l in merged_df if 'cc' in l and i in l \
                                           and 'visits' not in l]] == 1).any(axis=1))
    n = merged_df['therapy' + i].sum()
    print('At ' + i + ' follow-up ' + str(n) + ' (' + str(round(n/len(merged_df) * 100)) + '%)' + \
          ' had either counselling, face-to-face CBT or computer-based CBT')
merged_df['therapy'] = (merged_df[['therapy6wks', 'therapy12wks']] == True).any(axis=1).astype(float)
print('In total ' + str(merged_df['therapy'].sum()))

At 6wks follow-up 42 (6%) had either counselling, face-to-face CBT or computer-based CBT
At 12wks follow-up 43 (7%) had either counselling, face-to-face CBT or computer-based CBT
In total 62.0

In [6]:
# Import data containing information about medication changes from CRF
# question1 - medication 1=yes 2=no
# _question2 - date randomised
# _question3 - date 12 week follow-up completed

dtafile ='../../data/trial_data/Medications data from CRF/'\
'PANDA_Redpill_medications.dta'
df_med, meta = pyreadstat.read_dta(dtafile)
display(df_med[df_med['question1']==1].head())

# question7 - medication
# _question6 - prescription date

dtafile ='../../data/trial_data/Medications data from CRF/'\
'PANDA_Redpill_medications_summary.dta'
df_med_extended, meta = pyreadstat.read_dta(dtafile)

for k, i in enumerate(df_med['parentId']):
    idx = df_med_extended['parentId'] == i
    df_med_extended.loc[idx, 'identifier_n'] = pd.to_numeric(df_med['identifier'].iloc[k])

df_med_extended['medication'] = df_med_extended['question7'].str.lower()
df_med_extended['issuedata'] = df_med_extended['_question6']
df_med_extended.head()

   identifier  question1  _question2  _question3  parentId
1       40002          1  2015-09-22  2015-12-17       2.0
4       40042          1  2016-02-24  2016-05-24       5.0
6       40066          1  2016-04-11  2016-07-04       7.0
7       40096          1  2016-05-31  2016-08-23       8.0
12      40107          1  2016-06-13  2016-09-05      13.0

,id,parentId,question5,question6,question7,question8,question9,question10,question11,_question6,quantity,identifier_n,medication,issuedata
0,1,2,1,,Tamixosen,,1,90 days,,NaN,90.0,40002.0,tamixosen,NaN
1,2,5,1,08/04/2016,Omeprazole,20mg,2bd,28 capsules,1.3.5,2016-04-08,28.0,40042.0,omeprazole,2016-04-08
2,3,5,2,08/04/2016,Atorvastatin,20mg,1 Daily,28 capsules,Unknown,2016-04-08,28.0,40042.0,atorvastatin,2016-04-08
3,4,19,1,16/12/2016,Ranitidine,150mg,1 BD,60 tablets,unknown,2016-12-16,60.0,20109.0,ranitidine,2016-12-16
4,5,19,2,16/12/2016,Lansoprazole,30mg,1OD,28 capsules,unknown,2016-12-16,28.0,20109.0,lansoprazole,2016-12-16

In [7]:
# Patients taking other medication during the study
ids = df_med['identifier'][df_med['question1'] == 1].unique()
idx = merged_df['identifier_n'].isin(pd.to_numeric(ids))
merged_df['medication'] = 0
merged_df.loc[idx, 'medication'] = 1

In [8]:
medication_list = df_med_extended['question7'].str.lower().value_counts()
print(len(medication_list))
for i in medication_list.index:
    print(i)

132
lansoprazole
ramipril
omeprazole
salbutamol
levothyroxine sodium
citalopram
levothyroxine
tiotropium bromide
isosorbide mononitra
naproxen
zopiclone
sertaline
propantheline bromid
metformin
sildenafil
nitrofurantoin
symbicort
aquagel lubricating
rosuvastatin
cetirizine
gabapentin
beclometasone diprop
mirtazapine
cholecalciferol
diltiazem hydrochlor
formoterol
chlorhexidine glucon
tramadol
aspirin
amoxicillin
apixaban
desogestrel
salofalk
pravastatin
simvastatin
oxbutynin
glyceryl trinitrate
flucloxacillin
bisoprolol
clarithromycin
propranolol
ferrous fumarate
duac once daily gel
candesartan
fluticasone propiona
loperamide
aluminium chloride
folic acid
quinine bisulfate
rivaroxaban
paracetamol
thiamine
movicol plain powder
fluticasone/salmeter
zapain
tamsolosin
hydrex 4% surg scrub
laxido ibuprofen
colesevelam
flucloxciclin
micolette enema
napraxen
gliclazide
neomyan/chlorohexidi
betamethasone valera
chorhexidineacetate*
fluoxitine
relvar ellipta inhal
umeclidnium bromide
sukkarto sr
tapentadol
ventolin inhaler
lyrica
promethazine hydrocl
rigevidon
clenil modulite
femoston
nazproxen
doxycycline
glidozide
varencline
romipril
certrizine
vareniciline
sertaline 50mg
promethazin hcl
mometasone 0.1%
clotrimazole 2%cream
testosterone
clobetasone
tamixosen
prednisilone
sumatriptan
enalapril
pregabalin
budesonide-formotero
amorolfine
zeletta
tamsulosin
dapagliflozin
loratadine
hypromellose
pregablin
filitium-d3
amlodipine
lanzoprazole
proguanil/atovaquone
revaxis vaccine
ranitidine
atorvastatin
amorolfinre
losartan
oxytetracycline
migraleve yellow
diazepam
colchicine
lonsoprazole
laxido orange
levest
hyoscine butylbromid
peppermint oil
lymecycline
benzoyl peroxide/ cl
maralone (anti-malar
complan shake
cenil modilite
zelleta
otomize ear spray
clotrimazole pressar
lactulose oral solut
metronidazole gel
lisinopril

In [9]:
# Get each medication labelled with description using chatGPT
medication_df = pd.read_csv('../../data/trial_data/panda_medication_list.csv')
medication_df

                  Medication         Description
0               lansoprazole        Acid-reducer
1                   ramipril      Blood-pressure
2                 omeprazole        Acid-reducer
3                 salbutamol      Bronchodilator
4       levothyroxine sodium             Thyroid
..                       ...                 ...
127        otomize ear spray       Ear-infection
128             clotrimazole  Topical-antifungal
129  lactulose oral solution        Constipation
130        metronidazole gel          Antibiotic
131               lisinopril      Blood-pressure

[132 rows x 2 columns]

In [10]:
# Medication in the category antidepressants
antidepressants_list = medication_df['Medication'][medication_df['Description'] == 'Depression'].to_list()
print(antidepressants_list)
antidepressants_list = [i for i in antidepressants_list if "sertraline" not in i]

merged_df['antidepressant'] = 0
for i in antidepressants_list:
    ids = df_med_extended['identifier_n'][df_med_extended['medication'] == i].unique()
    idx = merged_df['identifier_n'].isin(ids)
    merged_df.loc[idx, 'antidepressant'] = 1

['citalopram', 'sertraline', 'mirtazapine', 'fluoxetine', 'sertraline 50mg']

In [11]:
# Import data containing information about medication changes from GP records
# dateofbl - date randomised
dtafile ='/Users/jolandamalamud/phd/papers/git/panda_public/data/trial_data/'\
'Medications from GP electronic records/PANDA_GP practices_EMIS_medications.dta'
df_med_emis, meta = pyreadstat.read_dta(dtafile)
df_med_emis.head()

dtafile ='/Users/jolandamalamud/phd/papers/git/panda_public/data/trial_data/'\
'Medications from GP electronic records/PANDA_GP practices_EMIS_LateMedications.dta'
df_med_emis_late, meta = pyreadstat.read_dta(dtafile)
df_med_emis_late.sort_values('identifier')

,identifier,dateofbl,dfu12wks,_date,_issuedate,drugs,dose,quantity,nhscost,consultation_type,location,user,user_type
0,10437,2017-03-15,2017-06-07,NaN,2017-05-16,Atorvastatin 80mg tablets,take one nocte,28,,,,,
21,10437,2017-03-15,2017-06-07,NaN,2017-06-07,Allopurinol 300mg tablets,take one daily,28,,,,,
22,10437,2017-03-15,2017-06-07,NaN,2017-05-16,Atorvastatin 80mg tablets,take one nocte,28,,,,,
23,10437,2017-03-15,2017-06-07,NaN,2017-03-16,Furosemide 40mg tablets,2 to be taken each morning,56,,,,,
24,10437,2017-03-15,2017-06-07,NaN,2017-06-07,Ramipril 10mg capsule,take one daily,28,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,40202,2016-10-25,2017-04-06,2017-03-29,2017-01-13,Difflam 0.15% spray (Meda Pharmaceuticals Ltd),Use 4-8 Sprays Every One And A Half To Three H...,30,4.239,GP Surgery,UPPER NORWOOD GROUP PRACTICE,"AGYEI-BENHENE, Adwoa (Mrs)",Community Nurse
58,40202,2016-10-25,2017-04-06,2016-11-03,2017-03-29,Typhoid polysaccharide 25micrograms/0.5ml vacc...,As Directed,1,9.3,GP Surgery,UPPER NORWOOD GROUP PRACTICE,"RESEARCH, Research (Ms)",Senior Administrator
59,40202,2016-10-25,2017-04-06,2017-01-13,2017-03-29,Havrix Monodose vaccine suspension for injecti...,As Directed,1,22.14,GP Surgery,UPPER NORWOOD GROUP PRACTICE,"EVANS, Megan (Dr)",General Medical Practitioner
60,40261,2017-01-11,2017-04-08,2016-12-19,2017-02-13,Protopic 0.03% ointment (LEO Pharma),Apply Thinly Twice A Day,30,,GP Surgery,SMS Medical Pract,"SODHI, S M (Dr)",General Medical Practitioner
61,40261,2017-01-11,2017-04-08,2016-11-25,2017-02-13,Hydrocortisone 0.5% cream,Apply Thinly Twice A Day As Directed,15,,GP Surgery,SMS Medical Pract,"JAMAL, Shahla (Ms)",Manager

In [12]:
# Find antidepressants in list of drugs
for df_tmp in [df_med_emis, df_med_emis_late]:
    ids = df_tmp['identifier'].unique()
    idx = merged_df['identifier_n'].isin(pd.to_numeric(ids))
    merged_df.loc[idx, 'medication'] = 1
    
    df_ad_emis = pd.DataFrame()
    for i in antidepressants_list:
        df_ad_emis = pd.concat((df_ad_emis,df_tmp[df_tmp['drugs'].str.contains(i, case=False, na=False)]))
        
    ids = df_ad_emis['identifier'].unique()
    idx = merged_df['identifier_n'].isin(pd.to_numeric(ids))
    merged_df.loc[idx, 'antidepressant'] = 1

In [13]:
for i in ['medication', 'antidepressant']:
    n = merged_df[i].sum()
    print(str(n) + '(' + str(round(n/len(merged_df) * 100)) + '%)' + \
          ' patients took other ' + i + ' at some point during the study')
print(str(merged_df['withdrew'][merged_df['antidepressant']==1].sum().astype(int)) + \
         ' of those withdrew from the study')

345(53%) patients took other medication at some point during the study
20(3%) patients took other antidepressant at some point during the study
12 of those withdrew from the study

In [14]:
# Specify variables of interest in RCT
df_save = merged_df[['identifier_n', 'group'] + [i for i in ['gadtot', 'phqtot', 'becktot', 'phq1']] + \
                 [i + '_' + j + 'wk' for i in ['log_gadtot', 'log_phqtot', 'log_becktot', 'phq1'] \
                  for j in ['2', '6', '12']] + \
                 ['_site_n', 'cistotal_cat', 'depr_dur_2years', 'age', 'edu3', 'antidepressantsinpast', \
                  'sex', 'ethnic', 'fin3', 'empstat2', 'marstat3', 'cisdepscore', 'medication', \
                  'antidepressant', 'therapy'] + \
                ['adherence5_'  + i + 'wk' for i in ['2', '6', '12']] + \
                 ['adaptmorisky'  + i for i in ['', '6wk', '12wk']]]

# Rename column names
df_save.columns = ['ID', 'group'] + [i + '0' for i in ['gad', 'phq', 'bdi', 'anh']] + \
                [i + str(j) + 'log' for i in ['gad', 'phq', 'bdi', 'anh'] for j in range(1,4)] + \
                ['site', 'cis', 'dep', 'age', 'education', 'AD_past', \
                'sex', 'ethnic', 'fin', 'empstat', 'marstat', 'cisscore', 'medication', \
                'antidepressant', 'therapy'] + \
                ['tablet' + str(i) for i in range(1,4)] + \
                ['adaptmorisky' + str(i) for i in range(1,4)]

In [15]:
# Save DataFrame
df_save.to_csv('../../data/trial_data/gng_panda_data_extended.csv')